<?php
namespace App\Models;

use App\Models\Model;

class ArticleModel extends Model {

    public function __construt($conn, $tbName)
    {
        parent::__construt($conn, $tbName); // TODO: Change the autogenerated stub
    }

    public function getAll(): array
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }

    public function getById($id)
    {
        return parent::getById($id); // TODO: Change the autogenerated stub
    }
    public function edit($id, $article)
    {
        return parent::edit($id, $article); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }


}